require('meteor').setup({
  personal = true,
  dev = true,
  treesitter = {
    installed_parsers = {
      'bash',
      'bibtex',
      'c',
      'comment',
      'cpp',
      'dart',
      'graphql',
      'java',
      'javascript',
      'json',
      'latex',
      'lua',
      'markdown',
      'markdown_inline',
      'python',
      'query',
      'rust',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
    },
    treesitter_enabled_filetypes = {
      'bibtex',
      'c',
      'comment',
      'cpp',
      'dart',
      'graphql',
      'java',
      'javascript',
      'javascript.jsx',
      'javascriptreact',
      'json',
      'latex',
      'lua',
      'python',
      'rust',
      'svelte',
      'typescript',
      'typescriptreact',
      'vim',
    },
  },
})
